name: Anna Schneider
description: Pythonista, PhD, feminist, cleantechie, and a pretty good baker
social_links: <a href="//twitter.com/windupanna"><i class="fa fa-twitter-square fa-2x"></i></a>
    <a href="//github.com/aschn"><i class="fa fa-github-square fa-2x"></i></a>
    <a href="//www.linkedin.com/in/aschn"><i class="fa fa-linkedin-square fa-2x"></i></a>

meta_description: "Anna Schneider on the internet"

cover: 'assets/images/cover_crop.jpg'

#markdown: redcarpet
#highlighter: pygments
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://annaschneider.org'
google_analytics: 'UA-38209810-1'

# Details for the RSS feed generator
url:            'http://annaschneider.org'
author:         'Anna Schneider'
